[options]
; Atlas ERP - Odoo 20 Community (development config)
admin_passwd = admin
db_host = localhost
db_port = 5434
db_user = odoo
db_password = odoo
addons_path = odoo/addons,odoo/odoo/addons,custom_addons
data_dir = data
http_port = 8069
dbfilter = ^atlas$
without_demo = all
log_level = info
